//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizacao.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exibicoes
    {
        public Exibicoes()
        {
            this.Sonorizacoes = new HashSet<Sonorizacoes>();
        }
    
        public int ExibicaoID { get; set; }
        public int ProgramaID { get; set; }
        public int UnidadeID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual ICollection<Sonorizacoes> Sonorizacoes { get; set; }
    }
}
