//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizacao.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SincronizacaoHomologacaoEntitiesReportTest : DbContext
    {
        public SincronizacaoHomologacaoEntitiesReportTest()
            : base("name=SincronizacaoHomologacaoEntitiesReportTest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Exibicoes> Exibicoes { get; set; }
        public DbSet<MusicaSonorizacoes> MusicaSonorizacoes { get; set; }
        public DbSet<Sonorizacoes> Sonorizacoes { get; set; }
        public DbSet<TipoTrilhas> TipoTrilhas { get; set; }
    }
}
