//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizacao.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicaSonorizacoes
    {
        public int MusicaSonorizacaoID { get; set; }
        public int SonorizacaoID { get; set; }
        public int MusicaID { get; set; }
        public int ClassificacaoID { get; set; }
        public string Execucao { get; set; }
        public string Minutagem { get; set; }
        public bool Alterada { get; set; }
        public int TipoExibicaoID { get; set; }
        public int QuadroID { get; set; }
        public int ImportacaoID { get; set; }
        public int EditoraID { get; set; }
        public int GravadoraID { get; set; }
    
        public virtual Sonorizacoes Sonorizacoes { get; set; }
    }
}
