//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizacao.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonorizacoes
    {
        public Sonorizacoes()
        {
            this.MusicaSonorizacoes = new HashSet<MusicaSonorizacoes>();
        }
    
        public int SonorizacaoID { get; set; }
        public int ExibicaoID { get; set; }
        public int UsuarioID { get; set; }
        public string Observacao { get; set; }
        public bool PreAprovado { get; set; }
        public bool Aprovado { get; set; }
        public bool Aberto { get; set; }
        public System.DateTime AprovadoEm { get; set; }
    
        public virtual Exibicoes Exibicoes { get; set; }
        public virtual ICollection<MusicaSonorizacoes> MusicaSonorizacoes { get; set; }
    }
}
