//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizacao.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTrilhas
    {
        public int TipoTrilhaID { get; set; }
        public string Descricao { get; set; }
    }
}
