//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTTRIB
    {
        public int TRIB_CD_CODIGO { get; set; }
        public string TRIB_DS_TITULO { get; set; }
        public string TRIB_DS_AUTOR { get; set; }
        public string TRIB_DS_INTERPRETES { get; set; }
        public Nullable<int> TRIB_CD_DISCOTECA { get; set; }
        public string TRIB_CD_CD_TRILHA { get; set; }
        public string TRIB_DS_CD_TITLE { get; set; }
        public Nullable<int> TRIB_NR_TRACK { get; set; }
        public string TRIB_CD_TRILHA { get; set; }
        public string TRIB_DS_TRACK_TIME { get; set; }
        public string TRIB_DS_TRILHA { get; set; }
        public string TRIB_NM_ARQUIVO { get; set; }
    }
}
