//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTTREC
    {
        public int TREC_CD_CODIGO { get; set; }
        public string TREC_DS_TITULO { get; set; }
        public string TREC_DS_AUTOR { get; set; }
        public string TREC_DS_INTERPRETES { get; set; }
        public string TREC_DS_ISRC { get; set; }
        public string TREC_DS_TRACK_TIME { get; set; }
        public string TREC_DS_GENERO { get; set; }
        public Nullable<decimal> TREC_DS_TRACK { get; set; }
        public string TREC_NM_ARQUIVO { get; set; }
    }
}
