//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTISRC
    {
        public int ISRC_CD_CODIGO { get; set; }
        public string ISRC_DS_TITULO { get; set; }
        public string ISRC_DS_AUTORES { get; set; }
        public string ISRC_DS_INTERPRETES { get; set; }
        public string ISRC_DS_IFPI { get; set; }
        public string ISRC_DS_ISWC { get; set; }
        public string ISRC_DS_ISRC { get; set; }
        public string ISRC_DS_GRA { get; set; }
        public Nullable<double> ISRC_CD_ECAD { get; set; }
        public Nullable<bool> ISRC_FL_ATIVA { get; set; }
        public Nullable<System.DateTime> ISRC_DT_CARGA { get; set; }
        public string ISRC_DS_TRACK_TIME { get; set; }
        public Nullable<decimal> ISRC_FAIXA { get; set; }
        public string ISRC_NM_ARQUIVO { get; set; }
    }
}
