//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTMUSI
    {
        public int MUSI_CD_CODIGO { get; set; }
        public int SIQD_CD_CODIGO { get; set; }
        public int CLAS_CD_CODIGO { get; set; }
        public Nullable<int> ISRC_CD_CODIGO { get; set; }
        public string MUSI_HR_MINUTAGEM { get; set; }
        public Nullable<System.DateTime> MUSI_HR_TIMECODE_INICIAL { get; set; }
        public Nullable<System.DateTime> MUSI_HR_TIMECODE_FINAL { get; set; }
        public Nullable<bool> MUSI_FL_BAIXA { get; set; }
        public Nullable<System.DateTime> MUSI_DT_BAIXA { get; set; }
        public Nullable<int> TRIB_CD_CODIGO { get; set; }
        public Nullable<decimal> MUSI_PC_BAIXA { get; set; }
        public Nullable<int> TREC_CD_CODIGO { get; set; }
        public Nullable<bool> MUSI_FL_INCIDENTAL { get; set; }
        public Nullable<bool> MUSI_FL_PPOURRI { get; set; }
        public string LOGIN_USUARIO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
    }
}
