//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTUNID
    {
        public int UNID_CD_CODIGO { get; set; }
        public string UNID_DS_NOME { get; set; }
        public Nullable<int> UNID_CD_TIPO { get; set; }
        public string UNID_DS_UF { get; set; }
        public string UNID_DS_CIDADE { get; set; }
        public string UNID_DS_DESCRICAO { get; set; }
        public string UNID_DS_CNPJ { get; set; }
        public string UNID_DS_LOGRADOURO { get; set; }
        public string UNID_DS_CEP { get; set; }
        public string UNID_DS_CONTATO { get; set; }
        public string UNID_DS_RAZAO { get; set; }
    }
}
