//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTSLOG
    {
        public long SLOG_CD_CODIGO { get; set; }
        public string SLOG_DS_COMANDO { get; set; }
        public string SLOG_DS_DESCRICAO { get; set; }
        public Nullable<int> USUA_CD_CODIGO { get; set; }
        public Nullable<System.DateTime> SLOG_DT_DATA { get; set; }
        public string SLOG_DS_DESCRICAOINICIAL { get; set; }
    }
}
