//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTPROD
    {
        public int PROD_CD_CODIGO { get; set; }
        public Nullable<int> GENE_CD_CODIGO { get; set; }
        public string PROD_DS_NOME { get; set; }
        public string PROD_DS_ORDEM { get; set; }
        public Nullable<bool> PROD_FL_ATIVO { get; set; }
        public string PROD_DS_ORDEM_INATIVO { get; set; }
    }
}
