//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTPRCL
    {
        public int PRCL_CD_CODIGO { get; set; }
        public int PREC_CD_CODIGO { get; set; }
        public Nullable<int> CLAS_CD_CODIGO { get; set; }
        public decimal PRCL_VL_VALOR { get; set; }
        public string PRCL_DS_ABRANGENCIA { get; set; }
    }
}
