//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTPREC
    {
        public int PREC_CD_CODIGO { get; set; }
        public System.DateTime PREC_DT_VIGENCIA_INICIO { get; set; }
        public System.DateTime PREC_DT_VIGENCIA_FIM { get; set; }
        public string PREC_DS_ASSOCIACAO { get; set; }
        public Nullable<int> ASSO_CD_CODIGO { get; set; }
    }
}
