//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTEXIB
    {
        public int EXIB_CD_CODIGO { get; set; }
        public string EXIB_DS_DESCRICAO { get; set; }
    }
}
