//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTWFNC
    {
        public int WFNC_CD_CODIGO { get; set; }
        public int SINC_CD_CODIGO { get; set; }
        public string WFNC_CD_ETAPA { get; set; }
        public Nullable<int> USUA_CD_USUARIO { get; set; }
        public Nullable<bool> WFNC_CD_WF { get; set; }
        public Nullable<System.DateTime> WFNC_DT_DATA { get; set; }
        public string WFNC_DS_DESCRICAO { get; set; }
    }
}
