//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTAUTO
    {
        public int AUTO_CD_CODIGO { get; set; }
        public Nullable<System.DateTime> AUTO_DT_CRIACAO { get; set; }
        public int USUA_CD_CRIADOR { get; set; }
        public Nullable<int> MUSI_CD_CODIGO { get; set; }
        public string AUTO_DS_MIME { get; set; }
        public Nullable<decimal> AUTO_VL_PORCENTAGEM { get; set; }
        public Nullable<decimal> AUTO_VL_VALOR { get; set; }
        public Nullable<int> PREC_CD_CODIGO { get; set; }
        public Nullable<System.DateTime> AUTO_DT_VENCIMENTO { get; set; }
        public Nullable<int> EDIT_CD_CODIGO { get; set; }
        public string auto_ds_obs { get; set; }
    }
}
