//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTEDIT
    {
        public int EDIT_CD_CODIGO { get; set; }
        public string EDIT_DS_NOME { get; set; }
        public string EDIT_DS_IDENT { get; set; }
        public Nullable<int> ASSO_CD_CODIGO { get; set; }
    }
}
