//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINCTSIQD
    {
        public int SIQD_CD_CODIGO { get; set; }
        public int QUAD_CD_CODIGO { get; set; }
        public int SINC_CD_CODIGO { get; set; }
        public Nullable<int> EXIB_CD_CODIGO { get; set; }
        public string SIQD_DS_TITULO { get; set; }
        public string SIQD_DS_DESCRICAO { get; set; }
        public Nullable<int> SIQD_CD_CODIGO_REPR { get; set; }
        public string SIQD_DS_REPR { get; set; }
    }
}
