//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincronizacaoMusical.MigrationDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class trilhas_vetrix
    {
        public string codigo_vetrix { get; set; }
        public System.DateTime data_roteiro { get; set; }
        public string exibidora { get; set; }
        public string programa { get; set; }
        public System.DateTime data_exibicao { get; set; }
        public string duracao { get; set; }
        public string trilha { get; set; }
        public string interprete { get; set; }
        public string status { get; set; }
        public string isrc { get; set; }
        public string codigo_record { get; set; }
        public string processado { get; set; }
        public string razao_social { get; set; }
        public string aovivo { get; set; }
        public string codigo_album { get; set; }
        public string album { get; set; }
        public string log_processado { get; set; }
        public Nullable<System.DateTime> data_processado { get; set; }
        public Nullable<System.DateTime> DtInsert { get; set; }
    }
}
